import ConnectionsPanelComponent from '../components/panels/ConnectionsPanel.vue';
import ChatPanelComponent from '../components/panels/ChatPanel.vue';
import RightPanelComponent from '../components/panels/RightPanel.vue';
import BottomPanelComponent from '../components/panels/BottomPanel.vue';
import { createPanelWrapper, type InjectMap } from '../composables/panel-wrapper-factory';

const connectionsInjects: InjectMap = {
  connections: { unwrapRef: true, defaultValue: [] },
  activeConnectionId: { unwrapRef: true, defaultValue: '' },
  sessionStatusLabel: {},
  onSelectConnection: {},
  onContextMenu: {},
};

const chatInjects: InjectMap = {
  activeConnectionId: { prop: 'connectionId', unwrapRef: true, defaultValue: '' },
  apiFetchForConnection: {},
  sessionId: { unwrapRef: true, defaultValue: '' },
  sessionTitle: { unwrapRef: true, defaultValue: '' },
  messages: { unwrapRef: true, defaultValue: [] },
  capabilities: { unwrapRef: true, defaultValue: null },
  sessionWorking: { unwrapRef: true, defaultValue: false },
  sessionError: { unwrapRef: true, defaultValue: null },
  permissions: { unwrapRef: true, defaultValue: [] },
  permissionsLoading: { unwrapRef: true, defaultValue: false },
  permissionsError: { unwrapRef: true, defaultValue: null },
  questions: { unwrapRef: true, defaultValue: [] },
  questionsLoading: { unwrapRef: true, defaultValue: false },
  questionsError: { unwrapRef: true, defaultValue: null },
  questionAnswerDrafts: { defaultValue: {} },
  agentOptions: { unwrapRef: true, defaultValue: [] },
  modelOptions: { unwrapRef: true, defaultValue: [] },
  commandOptions: { unwrapRef: true, defaultValue: [] },
  sessionShared: { unwrapRef: true, defaultValue: false },
  sessionShareUrl: { unwrapRef: true, defaultValue: '' },
  sessionActionWorking: { unwrapRef: true, defaultValue: false },
  sessionActionStatus: { unwrapRef: true, defaultValue: null },
  messagesHasOlder: { unwrapRef: true, defaultValue: true },
  messagesLoadingOlder: { unwrapRef: true, defaultValue: false },
  onSendPrompt: {},
  onAbort: {},
  onForkSession: {},
  onShareSession: {},
  onUnshareSession: {},
  onSummarizeSession: {},
  onRevertSession: {},
  onUnrevertSession: {},
  onLoadOlderMessages: {},
  onGrantPermission: {},
  onDenyPermission: {},
  onUpdateQuestionAnswer: { prop: 'onUpdate:questionAnswer' },
  onReplyQuestion: {},
  onRejectQuestion: {},
};

const rightPanelInjects: InjectMap = {
  activeConnectionId: { unwrapRef: true, defaultValue: '' },
  sessionId: { unwrapRef: true, defaultValue: '' },
  capabilities: { unwrapRef: true, defaultValue: null },
  diffs: { unwrapRef: true, defaultValue: [] },
  diffsLoading: { unwrapRef: true, defaultValue: false },
  diffsError: { unwrapRef: true, defaultValue: null },
  selectedDiffIndex: { unwrapRef: true, defaultValue: 0 },
  diffViewMode: { unwrapRef: true, defaultValue: 'unified' },
  diffExpanded: { unwrapRef: true, defaultValue: true },
  messages: { prop: 'rawMessages', unwrapRef: true, defaultValue: [] },
  totalCost: { unwrapRef: true, defaultValue: 0 },
  lastAgent: { unwrapRef: true, defaultValue: '' },
  lastModelLabel: { unwrapRef: true, defaultValue: '' },
  permissions: { unwrapRef: true, defaultValue: [] },
  permissionsLoading: { unwrapRef: true, defaultValue: false },
  permissionsError: { unwrapRef: true, defaultValue: null },
  autoAcceptPermissions: { unwrapRef: true, defaultValue: false },
  questions: { unwrapRef: true, defaultValue: [] },
  questionsLoading: { unwrapRef: true, defaultValue: false },
  questionsError: { unwrapRef: true, defaultValue: null },
  questionAnswerDrafts: { defaultValue: {} },
  todos: { unwrapRef: true, defaultValue: [] },
  todosLoading: { unwrapRef: true, defaultValue: false },
  todosError: { unwrapRef: true, defaultValue: null },
  fileTree: { unwrapRef: true, defaultValue: [] },
  fileContent: { unwrapRef: true, defaultValue: '' },
  searchPattern: { unwrapRef: true, defaultValue: '' },
  searchResults: { unwrapRef: true, defaultValue: [] },
  codumentTracks: { unwrapRef: true, defaultValue: [] },
  codumentTracksLoading: { unwrapRef: true, defaultValue: false },
  codumentTracksError: { unwrapRef: true, defaultValue: null },
  selectedCodumentTrackId: { unwrapRef: true, defaultValue: '' },
  boundCodumentTrackId: { unwrapRef: true, defaultValue: '' },
  codumentTrackTree: { unwrapRef: true, defaultValue: null },
  codumentTrackTreeLoading: { unwrapRef: true, defaultValue: false },
  codumentTrackTreeError: { unwrapRef: true, defaultValue: null },
  onRefreshDiffs: {},
  onUpdateDiffViewMode: { prop: 'onUpdate:diffViewMode' },
  onToggleDiffExpanded: {},
  onSelectDiff: {},
  onOpenDiffFile: {},
  onRefreshPermissions: {},
  onUpdateAutoAcceptPermissions: { prop: 'onUpdate:autoAcceptPermissions' },
  onGrantPermission: {},
  onDenyPermission: {},
  onRefreshQuestions: {},
  onUpdateQuestionAnswer: { prop: 'onUpdate:questionAnswer' },
  onReplyQuestion: {},
  onRejectQuestion: {},
  onRefreshTodos: {},
  onLoadFile: {},
  onLoadDirectory: {},
  onUpdateSearchPattern: { prop: 'onUpdate:searchPattern' },
  onRunSearch: {},
  onRefreshCodumentTracks: {},
  onUpdateCodumentTrackId: { prop: 'onUpdate:codumentTrackId' },
  onBindCodumentTrack: {},
  codumentAutoRefreshEnabled: { unwrapRef: true, defaultValue: true },
  onUpdateCodumentAutoRefreshEnabled: { prop: 'onUpdate:codumentAutoRefreshEnabled' },
};

const bottomPanelInjects: InjectMap = {
  bottomPanelOpen: { unwrapRef: true, defaultValue: true },
  onToggleBottomPanel: {},
};

export const dockviewPanelComponents = {
  connections: createPanelWrapper(ConnectionsPanelComponent, connectionsInjects, {}, 'ConnectionsPanelWrapper'),
  chat: createPanelWrapper(ChatPanelComponent, chatInjects, {}, 'ChatPanelWrapper'),
  'right-files': createPanelWrapper(RightPanelComponent, rightPanelInjects, { mode: 'files' }, 'RightPanelFilesWrapper'),
  'right-review': createPanelWrapper(RightPanelComponent, rightPanelInjects, { mode: 'review' }, 'RightPanelReviewWrapper'),
  'right-context': createPanelWrapper(RightPanelComponent, rightPanelInjects, { mode: 'context' }, 'RightPanelContextWrapper'),
  'right-todo': createPanelWrapper(RightPanelComponent, rightPanelInjects, { mode: 'todo' }, 'RightPanelTodoWrapper'),
  'right-codument': createPanelWrapper(RightPanelComponent, rightPanelInjects, { mode: 'codument' }, 'RightPanelCodumentWrapper'),
  'bottom-terminal': createPanelWrapper(BottomPanelComponent, bottomPanelInjects, { mode: 'terminal' }, 'BottomPanelTerminalWrapper'),
  'bottom-console': createPanelWrapper(BottomPanelComponent, bottomPanelInjects, { mode: 'console' }, 'BottomPanelConsoleWrapper'),
};
